version: '3.2'
services:
  db:
    image: "postgres"
    environment:
      POSTGRES_DB: 'teapot_backend_dev'
      POSTGRES_USER: 'docker'
      POSTGRES_PASSWORD: 'secret'
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - './docker/db/data:/var/lib/postgresql/data:delegated'
      - './docker/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:delegated'

  stripe-mock:
    image: "stripe/stripe-mock:latest"
    ports:
      - 12111:12111
      - 12112:12112